### ISSUE TITLE
SYLT (synchronized lyrics/text) support?

### ISSUE THREAD

**Issue by emk** [jameshurst/rust-id3#1]
Hello, and thank you for writing a really useful Rust library!

I'm currently working on a [subtitle processing tool for students of foreign languages](https://github.com/emk/substudy), and I'd love to add support for [the id3v2.3 SYLT tag, which handles synchronized lyrics](http://id3.org/id3v2.3.0#Synchronised_lyrics.2Ftext). Is there any easy way to access these fields using your library? I'd be perfectly happy to just get & set the raw binary data, if that's easiest for you, but I'd also be interested in contributing a nice API if you wish.

Thank you once again for contributing to the Rust ecosystem!

**Comment by polyfloyd** [comment]
Hi @emk,

I have implemented support for SYLT tags in the current master. If this issue is still relevant to you after 5 years, you might be interested in testing the new changes.

I will close this issue now.

**Comment by emk** [comment]
Thank you very much! I may actually have a use for this at some point, even after all these years!
