### ISSUE TITLE
UFID

### ISSUE THREAD

**Issue by rembo10** [jameshurst/rust-id3#13]
Hey, maybe this is a dumb question but how do I get the UFID tag?

**Comment by jameshurst** [comment]
You can get the UFID tag by using [`tag.get("UFID")`](http://jameshurst.github.io/rust-id3/id3/struct.Tag.html#method.get).

**Comment by rembo10** [comment]
Ah OK, and then access the content with unknown()?

**Comment by jameshurst** [comment]
Since this is a text type frame (indicated by the T prefix) the contents can be accessed using [text()](http://jameshurst.github.io/rust-id3/id3/frame/enum.Content.html#method.text).
