### ISSUE TITLE
Allocations based on untrusted input

### ISSUE THREAD

**Issue by tehmatt** [jameshurst/rust-id3#15]
For example, `src/frame/stream/v3.rs::read` allocates a vector of size `content_size`, which is read directly from the input.  As this can cause an unhandleable OOM error, it's rather inconvenient.

I've solved this for myself by putting arbitrary size bounds at the locations that are causing me problems, but there's probably a better solution.

**Comment by polyfloyd** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/ID3#ID3v2), the size of a tag is limited to 256MB. The easiest (but dirty) fix would be to use this as an upper bound.

But it would be better to rewrite the parser to read directly from an `io::Read` instead of a buffer.

**Comment by polyfloyd** [comment]
As of 0.2, the decoder has been rewritten to use byte streams, eliminating most if not all vulnerable allocations.
