### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by polyfloyd** [jameshurst/rust-id3#16]
So far, this is the best Rust library for reading ID3 tags that I've seen, but it could still use some work.

I'd like to help out by refactoring the code to make it more compliant to Rust's standards. Of course I could just create a fork, but before I do so, wanted to check with you whether you're open to merging the improvements proposed I propose:

Mutable state:
* `Frame::new` creates a new frame with it's content set to Unknown with no content, after this, manual initialization is needed which requires the frame to be mutable
* `Tag::set_version` works by performing a lot of internal mutations, [which can fail](https://github.com/jameshurst/rust-id3/blob/master/src/tag.rs#L340), on the frames it contains. which will let the frame end up in an undefined state. A better approach would be to introduce a new initializer like `Tag::from_tag` which returns a `Result::Err` on failure

The internals are not well hidden. The public API should expose only the types and functions absolutely needed to interact with the library. Having lots of public internals also clutters the documentation:
* `Frame::uuid` and `generate_uuid`
* `Picture::from_u8` and `Encoding::from_u8`
* `Flags::from_byte` and `Flags::to_byte`
* `Frame::content_to_bytes`
* `Tag::frames` breaks encapsulation by returning a reference to the contained vector instead of a slice or iterator.
* The encoding of individual frames can be controlled with the `Tag::set_*_enc` functions. Cool, but is this really worth maintaining all these almost identical functions? If users really want to set the encoding per frame, the API would be a whole lot simpler if all advanced frame manipulation went through the existing `Tag::push` function.

Runtime validation is done where compile-time validation is possible:
* The tag version is passed around as a single byte requiring validation. Said validation also varies across the API: `Frame::read_from` and `Frame::write_to` return an error, but `Tag::with_version` panics. If an enum is used, the check has to happen only once.

Integration with std:
* `Timestamp::parse` could make better use of the [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html) trait
* `Tag::get_all` could return an iterator instead of a vector.
* `Frame` does not implement `fmt::Debug`

Implementation details:
* Lengthy match expressions are used instead of the shorter `and_then`, `map`, `or_else` methods of Option and Result. E.g. `Tag::disc_pair`
* There are a lot of macros which could be replaced with templated functions. 
* `Tag` is very highly coupled with the reader/writer. This requires functions mutating a tag to perform actions to keep some state that the writer uses 
* `Tag::text_for_frame_id` and similar functions return the contents of already existing types. E.g. `Tag::lyrics` returns just the text while a `frame::Lyrics` can return all associated data
* Reading and writing is scattered around
* `Tag:add_*` has a very confusing name because they don't just add stuff, they also remove anything with a conflicting unique identifier.
* When updating a tag in an audio file, there does not seem to be any guarantee that a tag grown in size does not overwrite the audio data.

I'm going to stop extending this list now. If anything seems unfamiliar I'll be happy to offer an explanation. :)

**Comment by jameshurst** [comment]
Hey @polyfloyd, I definitely agree that the library could use some cleaning up and a more user friendly API. I haven't been using this library much myself recently so improvements have been few and far between. I would be happy to add you as a collaborator on the repository so you could make the proposed changes if you are interested in that.

**Comment by polyfloyd** [comment]
Yes, I'd love to help out!

**Comment by jameshurst** [comment]
Great! I've sent you an invite to be a collaborator on the repository.

**Comment by polyfloyd** [comment]
@jameshurst I've been hacking away for a week now and pushed some changes proposed in this issue to master. However, because implementing some improvements cause considerable API breakage I've started pushing to a separate branch, `storage-wip`. I'm planning on merging this branch to master when I'm done refactoring.

If you'd like, you can have a look at how things are progressing. This is a summary of what I've done so far:
* Decoupled Tag and Frame from the encoder by introducing a new storage system
* Implemented Eq for Frame in a way that allows it to be used for detecting duplicate frames
  * Used this to get rid of Frame::uuid
* Made Tag and Frame version agnostic by storing all frames as as IDv2.4
  * The version should now be specified when writing a tag
* Exposed the ID3v1 module so this does not have to be handled the v2 Tag
  * v1::Tag can be converted to a v2 tag via the From trait
* Various tweaks to the getters and setters of Tag
* Added tests for reading and writing real world tags

**Comment by jameshurst** [comment]
@polyfloyd Sounds great! I'll take a look.

**Comment by polyfloyd** [comment]
@jameshurst Hey James, It's been a while and I think that the most important issues have been resolved. What do you think, shall we tag and release 0.2?

**Comment by jameshurst** [comment]
@polyfloyd I think a 0.2 release sounds good to me!
