### ISSUE TITLE
Panic while reading tag

### ISSUE THREAD

**Issue by foxtrot94** [jameshurst/rust-id3#17]
Updated to v0.2 today and it broke while going through files that worked with v0.1.12.

The culprit seems to be [src\frame\mod.rs line 76](../tree/master/src/frame/mod.rs#L76). I'll be reverting back to 0.1.12 for the time being.

## Stack trace
		0: std::sys_common::backtrace::_print
				 at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
		1: std::panicking::default_hook::{{closure}}
				 at C:\projects\rust\src\libstd\panicking.rs:380
		2: std::panicking::default_hook
				 at C:\projects\rust\src\libstd\panicking.rs:397
		3: std::panicking::rust_panic_with_hook
				 at C:\projects\rust\src\libstd\panicking.rs:577
		4: std::panicking::begin_panic<alloc::string::String>
				 at C:\projects\rust\src\libstd\panicking.rs:538
		5: std::panicking::begin_panic_fmt
				 at C:\projects\rust\src\libstd\panicking.rs:522
		6: std::panicking::rust_begin_panic
				 at C:\projects\rust\src\libstd\panicking.rs:498
		7: core::panicking::panic_fmt
				 at C:\projects\rust\src\libcore\panicking.rs:71
		8: core::panicking::panic
				 at C:\projects\rust\src\libcore\panicking.rs:51
		9: core::option::Option<str*>::unwrap<str*>
				 at C:\projects\rust\src\libcore\macros.rs:22
		10: id3::frame::Frame::with_content
				 at C:\Users\Javier Fajardo\.cargo\registry\src\github.com-1ecc6299db9ec823\id3-0.2.0\src\frame\mod.rs:76
		11: id3::stream::frame::v2::decode<std::io::buffered::BufReader<std::fs::File>>
				 at C:\Users\Javier Fajardo\.cargo\registry\src\github.com-1ecc6299db9ec823\id3-0.2.0\src\stream\frame\v2.rs:22
		12: id3::stream::frame::decode<std::io::buffered::BufReader<std::fs::File>>
				 at C:\Users\Javier Fajardo\.cargo\registry\src\github.com-1ecc6299db9ec823\id3-0.2.0\src\stream\frame\mod.rs:16
		13: id3::stream::tag::decode<std::io::buffered::BufReader<std::fs::File>>
				 at C:\Users\Javier Fajardo\.cargo\registry\src\github.com-1ecc6299db9ec823\id3-0.2.0\src\stream\tag.rs:76
		14: id3::tag::Tag::read_from<std::io::buffered::BufReader<std::fs::File>>
				 at C:\Users\Javier Fajardo\.cargo\registry\src\github.com-1ecc6299db9ec823\id3-0.2.0\src\tag.rs:1359
		15: id3::tag::Tag::read_from_path<std::path::Path*>
				 at C:\Users\Javier Fajardo\.cargo\registry\src\github.com-1ecc6299db9ec823\id3-0.2.0\src\tag.rs:1365

**Comment by polyfloyd** [comment]
Hi foxtrot, thank you for reporting this issue!

Would it be possible for you to send me the file containing the troublesome ID3v2 tag?

**Comment by foxtrot94** [comment]
Hi @polyfloyd, I've attached the file in question to this issue: [rust-id3-bugged-song.zip](https://github.com/jameshurst/rust-id3/files/1297023/rust-id3-bugged-song.zip)

The bug seems to be easy to reproduce with that file. Let me know if there's anything else I can help with or if you need more info.

**Comment by polyfloyd** [comment]
Okay, I think I got it. The tag you are trying to load has ID3 version 2.2. Version 0.1.12 stored the frames of 2.2 tags as-is without touching the IDs it read.

0.2 decouples the storage format from it's data structure by storing all ID3v2 tags as 2.4 which requires mapping them to their 2.4 equivalent, a conversion which was previously separate from decoding.

Your tag can not be decoded because it contains frames which IDs are not known to the mapping in util.rs., something which can easily be fixed by adding them.

**Comment by jameshurst** [comment]
I think a possible solution here might be to store the frame ID internally as a `String`, while converting the internal representation to an ID3v2.4 ID if possible and storing the given ID if it cannot be converted. This way any unknown IDs won't cause failures and would be written back with the tag.

**Comment by polyfloyd** [comment]
Yes, that sounds like a good idea. But I would recommend using an `enum` instead of just a `String` to be able to tell valid 2.4 IDs from invalid 2.2 IDs. This also solves my mistake of letting `Frame::with_content` panic on invalid input without having to change the function signature.

**Comment by foxtrot94** [comment]
Confirmed fix! Thanks!
