### ISSUE TITLE
Panic while saving an ID3v2.4 tag

### ISSUE THREAD

**Issue by foxtrot94** [jameshurst/rust-id3#18]
Updated to latest commit from `master` branch and got a panic. This seems to also happen in v0.2 and v0.1.12. It seems to be easily reproducible with [this file](https://github.com/jameshurst/rust-id3/files/1319563/tag_saving_error_file.zip).

## Stack Trace
		0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
				 at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
		1: std::sys_common::backtrace::_print
				 at /checkout/src/libstd/sys_common/backtrace.rs:71
		2: std::panicking::default_hook::{{closure}}
				 at /checkout/src/libstd/sys_common/backtrace.rs:60
				 at /checkout/src/libstd/panicking.rs:381
		3: std::panicking::default_hook
				 at /checkout/src/libstd/panicking.rs:397
		4: std::panicking::rust_panic_with_hook
				 at /checkout/src/libstd/panicking.rs:577
		5: std::panicking::begin_panic
				 at /checkout/src/libstd/panicking.rs:538
		6: std::panicking::begin_panic_fmt
				 at /checkout/src/libstd/panicking.rs:522
		7: rust_begin_unwind
				 at /checkout/src/libstd/panicking.rs:498
		8: core::panicking::panic_fmt
				 at /checkout/src/libcore/panicking.rs:71
		9: core::str::slice_error_fail
				 at /checkout/src/libcore/str/mod.rs:2218
		10: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index::{{closure}}
				 at /checkout/src/libcore/str/mod.rs:1941
		11: <core::option::Option<T>>::unwrap_or_else
				 at /checkout/src/libcore/option.rs:370
		12: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index
				 at /checkout/src/libcore/str/mod.rs:1941
		13: core::str::traits::<impl core::ops::index::Index<core::ops::range::RangeTo<usize>> for str>::index
				 at /checkout/src/libcore/str/mod.rs:1705
		14: <alloc::string::String as core::ops::index::Index<core::ops::range::RangeTo<usize>>>::index
				 at /checkout/src/liballoc/string.rs:1863
		15: id3::stream::frame::content::comment_to_bytes
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/stream/frame/content.rs:143
		16: id3::stream::frame::content::encode
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/stream/frame/content.rs:41
		17: id3::stream::frame::v4::encode
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/stream/frame/v4.rs:69
		18: id3::stream::frame::encode
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/stream/frame/mod.rs:57
		19: id3::stream::tag::Encoder::encode
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/stream/tag.rs:119
		20: id3::tag::Tag::write_to
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/tag.rs:1371
		21: id3::tag::Tag::write_to_path
				 at /home/omaha/.cargo/git/checkouts/rust-id3-61c2a240b6004f52/16e7ce7/src/tag.rs:1388

**Comment by polyfloyd** [comment]
The panic seems to be caused by a comment that has a language of length < 3 set. The file attached does not seem to contain comments, are you adding it yourself? If so, Try setting the language to e.g. "eng".

But yes, this is a bug. We should not panic like this. We can solve this by either aborting with an error or adding a padding, although the lather does not seem to be described by the spec.

Looking at the code, `lyrics_to_bytes` seems to suffer from the same problem.

**Comment by foxtrot94** [comment]
I took a look at the data that I'm trying to add and there seems nothing out of the ordinary. I'm updating the Album, Album Artist, Track Number, Year and Genre frames.

The best case scenario would be to add padding to the frame content and continue writing the tag. Some of the files that I'm working with are quite old and have a lot of differently written tags with a variety of string encodings (UTF-8, UTF-16). They're also in a couple of different languages (German, Spanish, Korean, Japanese), so I can't assume that it'll always be English.
