### ISSUE TITLE
can't add frames with ids in DEFAULT_FILE_DISCARD

### ISSUE THREAD

**Issue by ahti** [jameshurst/rust-id3#25]
I have a problem trying to add a MLLT frame to an audio file.

[This expression](https://github.com/jameshurst/rust-id3/blob/e0d3afeeb1b7b2de0a35864769a80470d2c8cabf/src/stream/tag.rs#L116) is what i'm talking about specifically:

```rust
let saved_frames = tag.frames()
    .filter(|frame| {
        !(frame.tag_alter_preservation()
          || (frame.file_alter_preservation()
              || DEFAULT_FILE_DISCARD.contains(&frame.id())))
    });
```

This makes it impossible to use the crate to add frames from `DEFAULT_FILE_DISCARD`, which contains MLLT.

This filter should probably only be applied to frames that were initially read from a file, and only if the tag is modified. I'm also not sure this needs to check the file alter preservation flag at all, since we are only modifying the tag, right?

**Comment by polyfloyd** [comment]
Hey ahti, thank you for your feedback!

Yes, it seems we are too eager to discard tags. The `DEFAULT_FILE_DISCARD` filter should only be applied when the files contents are changed.
