### ISSUE TITLE
Should `Tag::is_candidate` and `v1::Tag::is_candidate` consume their reader?

### ISSUE THREAD

**Issue by InputUsername** [jameshurst/rust-id3#29]
`Tag::is_candidate` and `v1::Tag::is_candidate` don't take a reference to the reader which means the reader can't be used anymore (correct me if I'm wrong; very new to Rust). Is there a reason for not accepting it as `&mut R`?

I'm asking because I'm writing some code to figure out the type of an mp3 file (bare mp3 without any tags, mp3 with only a v1 tag, or mp3 with a v2 tag). To distinguish these I want to use the methods for `Tag` and `v1::Tag` on the same reader but that doesn't work. Creating a new reader for each call seems inefficient.

**Comment by polyfloyd** [comment]
Hey @InputUsername,

Have a look at [io::Read::by_ref](https://doc.rust-lang.org/stable/std/io/trait.Read.html#method.by_ref). It allows you to create a reference to a reader which you can pass to the respective `is_candidate` functions without having to reopen your file.

**Comment by InputUsername** [comment]
Looks like that works. Thank you!
