### ISSUE TITLE
StringDecoding([]): data is not valid utf-8

### ISSUE THREAD

**Issue by AndrewRadev** [jameshurst/rust-id3#30]
I'm trying to build a simple tool to embed cover art into mp3s, for my own personal usage. I'm running into an issue after writing the image -- once the `Tag` is written to that same file (it works, the cover art renders in my file manager and everything), the next time I try to read it with `Tag::read_from_path`, I get the following error:

```
StringDecoding([]): data is not valid utf-8
```

The full code is not a whole lot at the moment, and it looks like this: https://github.com/AndrewRadev/id3-image/blob/de5eae6d0c4fee18a15b5290208709780ec77bcf/src/main.rs

If I change the version to `Id3v24`, there's no problem writing, and then reading, tags from the file. Unfortunately, some other tools I use can't handle 2.4, and, ideally, I'd like to write tags using 2.3.

Weirdly enough, I *can* read embedded images in 2.3 tags in other mp3s, so maybe there's a bug when writing the image?

**Comment by AndrewRadev** [comment]
Thank you very much for the quick response. Unfortunately, while it doesn't error out on a second run, it also breaks in a different way now :). When I run it on a file with both v2.2 and v2.3 tags (not sure if that's relevant), it completely removes the v2.3 tags, instead of adding the cover art. Here's the `id3` tool's `-v` output before:

```
% id3 -v ~/Pillars\ of\ Eternity\ OST\ -\ Defiance\ Bay\ \(copy\ 1\).mp3
#file	/home/andrew/Pillars of Eternity OST - Defiance Bay (copy 1).mp3
#tag	ID3v2 3.0
{TIT2}
	Defiance Bay 
{TPE1}
	Pillars of Eternity OST
{TCON}
	Test
#tag	ID3 1.1
{Title}
	Defiance Bay 
{Artist}
	Pillars of Eternity OST
```

And then after:

```
% id3 -v ~/Pillars\ of\ Eternity\ OST\ -\ Defiance\ Bay\ \(copy\ 1\).mp3
#file	/home/andrew/Pillars of Eternity OST - Defiance Bay (copy 1).mp3
#tag	ID3 1.1
{Title}
	Defiance Bay 
{Artist}
	Pillars of Eternity OST
```

To compare, here's how it looked like before commit a3243a25abeb18cbdbf89c55bddf4ac287ce7bf4:

```
% id3 -v ~/Pillars\ of\ Eternity\ OST\ -\ Defiance\ Bay\ \(copy\ 1\).mp3  
#file	/home/andrew/Pillars of Eternity OST - Defiance Bay (copy 1).mp3
#tag	ID3v2 3.0
{TIT2}
	Defiance Bay 
{TPE1}
	Pillars of Eternity OST
{TCON}
	Test
{APIC}
	<binary data>
#tag	ID3 1.1
{Title}
	Defiance Bay 
{Artist}
	Pillars of Eternity OST
```

It does specifically seem to be this commit that's doing it -- I did a quick bisect, just in case some other change between cargo and master was the cause.

**Comment by polyfloyd** [comment]
Hey @AndrewRadev, I'm working on new integration tests to ensure better compatibility with other tools. I have discovered that the Squell ID3 program is able to read tags if `unsynchronisation` is turned off. Could you try to disable this by setting `.unsynchronisation(false)` on an `EncoderBuilder`?

**Comment by AndrewRadev** [comment]
Yes! That seems to do the trick.

I changed the code here to include an `.unsynchronisation(false)`: https://github.com/jameshurst/rust-id3/blob/64d98c8121e5bc2c00aad5dd71701a0985c867a0/src/tag.rs#L1153-L1157. It was easier to do it there than in my own package, since the `storage` module is not public and I would have had to import a bunch of stuff.

In any case, once I added that flag, on the `id3v23-size-fix` branch, I could write the image and it was immediately detected by my thumbnail manager, as before. This time, though, running it a second time didn't blow up. The `id3` tool I'm using is also detecting the v2.3 tags just fine, including the `APIC` tag.

Actually, now that I've browsed through the code a bit more, I found I can also use the unmodified `id3v23-size-fix` with this code in my own package:

``` rust
let encoder = id3::EncoderBuilder::default().
    version(id3::Version::Id3v23).
    unsynchronisation(false).
    build().
    unwrap();

if let Err(e) = encoder.encode_to_path(&tag, music_filename) {
    eprintln!("Error writing image to file: {}", e);
    process::exit(1);
}
```

So, if you merge the branch, this might be a good-enough-for-now fix for my needs. I'll continue helping out with debugging, if you'd like to come up with a more general solution.

**Comment by polyfloyd** [comment]
Excellent! I'll merge the size fix branch and do a few more tests. I will also disable unsynchonisation by default in the next release because this is not the first time it has caused problems like this and most tools are ID3 compatible anyway.

**Comment by AndrewRadev** [comment]
Awesome, thank you again for your work!
